# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.4.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: o33651150@gmail.com
author_name: HackerOSK
contract_name: rchain
deployment_language: python
preset_name: production
project_name: rchain-contracts

