# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.16
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: o33651150@gmail.com
author_name: HackerOSK
cloud_provider: none
contract_name: rchain
deployment_language: python
preset_name: production
project_name: rchain

